field: c09c2efd-1756-447f-8034-7a97af3a171e # About Content
fieldLayouts:
  74125585-75ef-4956-8e99-0881cc3b4dc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f521d771-e90b-4c71-9316-3d47d13b6868 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7252042f-075e-4569-b69c-b9fde7c99ec7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c912a548-de77-4ab1-bb84-87cd32164509 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa244ff5-43c9-48e4-8d44-438fae4c547a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 641fc2a3-cc17-4e5d-b8dc-2cde5e3ac850
        userCondition: null
fields:
  c912a548-de77-4ab1-bb84-87cd32164509: # Copy
    columnSuffix: guurngmg
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f521d771-e90b-4c71-9316-3d47d13b6868: # Heading
    columnSuffix: cpewjhsx
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: hobbiesAndInterests
name: 'Hobbies and Interests'
sortOrder: 2
