fieldLayouts:
  f413a308-652d-4220-b0c2-6ff8ab50d9e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb22cabe-8fb7-4a1a-ad92-2ab953669597
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f75332b-ac8d-4234-8499-fad16d02710c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e86e010-9462-4433-ae9d-3bae81bbe6bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 81f8846c-9df7-433a-a9a9-1fe2bdffddde
        userCondition: null
handle: contact
hasTitleField: true
name: Contact
section: 2979a581-df03-47da-9b70-9ad81fde2a2e # Top Level Pages
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
