fieldLayouts:
  745529b8-d341-4bc2-9506-89f116884e01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a867abc-c848-49e4-aad7-707cfe8e9383
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 570922d8-d425-4880-9eec-191e415af31f # Homepage Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a74a74a4-27eb-4a5a-8d67-84efb54360f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ccb1b90b-2d9c-4c54-bb18-fce9efdf0b32 # Homepage Strapline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5472dcf3-3fe1-4400-bd9c-0df760c61c3d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 277a7faf-e03e-4ecd-9625-02afda82fe94
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 6c4fbce3-00fb-468b-b92b-bf85829b2846 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
