fieldLayouts:
  bbd098fb-658a-4a07-a362-01fa8294ffec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 125f3346-0795-42db-859b-7fe1dd4d0157
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f75332b-ac8d-4234-8499-fad16d02710c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd75509d-e8a7-46fb-a853-9fbf17548aa7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 634b63c8-1c41-4182-bd74-dcb884686c87 # Resume
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e6d0007-b103-4752-bae7-d92d5c8d25c2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4bd8cbc7-438a-4c5a-8dc4-9e62a9877f8c
        userCondition: null
handle: resume
hasTitleField: true
name: Resume
section: 2979a581-df03-47da-9b70-9ad81fde2a2e # Top Level Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
