columnSuffix: adpjxfpd
contentColumnType: text
fieldGroup: 0179b7b4-dd3b-4ffd-ba09-0359e93357ef # Headers
handle: homepageHeader
instructions: null
name: 'Homepage Header'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
