columnSuffix: null
contentColumnType: string
fieldGroup: eb3c172c-232c-42ad-b0e0-f2bc7e76a5b0 # Files
handle: resume
instructions: null
name: Resume
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - pdf
  defaultUploadLocationSource: 'volume:5a9e8aa7-6196-4d4a-9671-fada6785066f' # Files
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:2302dd73-4e04-4686-b1c6-714f442ea962' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:5a9e8aa7-6196-4d4a-9671-fada6785066f' # Files
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
