changedFieldIndicator: 46703011
field: f65f3d28-d22c-45b0-a284-1091bca90a05 # SKill
fieldLayouts:
  1085a84c-7901-4c33-9f7b-9f67d245044a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ba0a35dc-4c94-4d79-8b9b-980b5a18875a # Skill Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebc6aa9b-30e7-4d50-830c-a85785bd3e89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b02c9884-6d15-4b53-8783-6fcd24847c0f # Skill Proficiency
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebaa2be8-7c19-4e9c-a727-ace9254983ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f15c7ae-655b-457a-8304-574b16df828c
        userCondition: null
fields:
  b02c9884-6d15-4b53-8783-6fcd24847c0f: # Skill Proficiency
    columnSuffix: zwurfrwr
    contentColumnType: integer(10)
    fieldGroup: null
    handle: skillProficiency
    instructions: null
    name: 'Skill Proficiency'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ba0a35dc-4c94-4d79-8b9b-980b5a18875a: # Skill Name
    columnSuffix: prqyfden
    contentColumnType: text
    fieldGroup: null
    handle: skillName
    instructions: null
    name: 'Skill Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
