changedFieldIndicator: 1504518250
field: 570922d8-d425-4880-9eec-191e415af31f # Homepage Header
fieldLayouts:
  d19eac2b-d8ba-4b06-9e0e-f58cfbf05f22:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 35cfebcd-2ad0-4e27-a568-7ba76ebcf928 # My Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeab8377-8ab9-455b-9ce8-ca082fa50430
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f115756f-2397-46bb-8de4-ee6a414a1a04 # Strapline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2b313de-c185-44be-8a3c-c59151dd31f7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 261a665e-68e3-48a3-bd72-b7f4d47da9e7
        userCondition: null
fields:
  35cfebcd-2ad0-4e27-a568-7ba76ebcf928: # My Name
    columnSuffix: rooeowvq
    contentColumnType: text
    fieldGroup: null
    handle: myName
    instructions: null
    name: 'My Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f115756f-2397-46bb-8de4-ee6a414a1a04: # Strapline
    columnSuffix: virwvagg
    contentColumnType: text
    fieldGroup: null
    handle: strapline
    instructions: null
    name: Strapline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
