defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  af0767db-5956-4eaa-9fdd-62f6302fe39c: # Shaun Lindsley
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
